In [35]:
## pandas 提供了新的資料結構

In [36]:
# run in bash shell
!pip install pandas

You should consider upgrading via the 'c:\users\paul\anaconda3\python.exe -m pip install --upgrade pip' command.


In [37]:
# run in python console
import pandas as pd

In [39]:
movie_ratings = [8.0, 7.3, 8.5, 8.6]
ser = pd.Series(movie_ratings)

<class 'pandas.core.series.Series'>
0    8.0
1    7.3
2    8.5
3    8.6
dtype: float64
8.6


In [40]:
# Pandas add index key.
print(type(ser))
print(ser)
print(ser[3])

<class 'pandas.core.series.Series'>
0    8.0
1    7.3
2    8.5
3    8.6
dtype: float64
8.6


In [42]:
movie_titles = ['The Avengers', 'Avengers: Age of Ultron', 'Avengers: Infinite War', 'Avengers: Endgame']
ser = pd.Series(movie_ratings, index = movie_titles)
ser

The Avengers               8.0
Avengers: Age of Ultron    7.3
Avengers: Infinite War     8.5
Avengers: Endgame          8.6
dtype: float64

In [43]:
type(ser.values)

numpy.ndarray

In [46]:
print(ser.values)
print(ser.index)

[8.  7.3 8.5 8.6]
Index(['The Avengers', 'Avengers: Age of Ultron', 'Avengers: Infinite War',
       'Avengers: Endgame'],
      dtype='object')


In [47]:
# Vectorization.
ser*10

The Avengers               80.0
Avengers: Age of Ultron    73.0
Avengers: Infinite War     85.0
Avengers: Endgame          86.0
dtype: float64

In [48]:
# Boolean type is applicable.
ser[ser >= 8]

The Avengers              8.0
Avengers: Infinite War    8.5
Avengers: Endgame         8.6
dtype: float64

In [50]:
ser['Avengers: Infinite War']

8.5

In [52]:
ser[2]

8.5

In [57]:
avengers = pd.DataFrame()
avengers['movie'] = movie_titles
avengers['rating'] = movie_ratings
avengers

movie  rating
0             The Avengers     8.0
1  Avengers: Age of Ultron     7.3
2   Avengers: Infinite War     8.5
3        Avengers: Endgame     8.6

In [58]:
type(avengers)

pandas.core.frame.DataFrame

In [59]:
avengers.index

RangeIndex(start=0, stop=4, step=1)

In [60]:
avengers.columns

Index(['movie', 'rating'], dtype='object')

In [65]:
avengers['movie'].values

array(['The Avengers', 'Avengers: Age of Ultron',
       'Avengers: Infinite War', 'Avengers: Endgame'], dtype=object)

In [68]:
avengers['movie'].values

array(['The Avengers', 'Avengers: Age of Ultron',
       'Avengers: Infinite War', 'Avengers: Endgame'], dtype=object)

In [69]:
# Set is useful for joint, union and independent...
odds_index = pd.Index([1, 3, 5, 7, 9])
primes_index = pd.Index([2, 3, 5, 7])
print(odds_index & primes_index) # and
print(odds_index | primes_index) # or
print(odds_index ^ primes_index) # exclusive or

Int64Index([3, 5, 7], dtype='int64')
Int64Index([1, 2, 3, 5, 7, 9], dtype='int64')
Int64Index([1, 2, 9], dtype='int64')


In [70]:
# Joint
odds_index & primes_index

Int64Index([3, 5, 7], dtype='int64')

In [71]:
odds_index | primes_index

Int64Index([1, 2, 3, 5, 7, 9], dtype='int64')

In [72]:
# XOR（Exclusive OR）
odds_index ^ primes_index

Int64Index([1, 2, 9], dtype='int64')

In [ ]:
odds_index ^ primes_index

In [73]:
odds_index.difference(primes_index)

Int64Index([1, 9], dtype='int64')

In [75]:
primes_index.difference(odds_index)

Int64Index([2], dtype='int64')

In [ ]:
...

In [76]:
movie_ratings = [9.0, 8.9, 8.8, 8.7]
ser = pd.Series(movie_ratings)
print(ser)

0    9.0
1    8.9
2    8.8
3    8.7
dtype: float64


In [77]:
movie_ratings = [9.0, 8.9, 8.8, 8.7]
movie_titles = ["The Dark Knight", "Schindler's List", "Forrest Gump", "Inception"]
ser = pd.Series(movie_ratings, index=movie_titles)
print(ser.index)
print(ser.values)
print(ser)

Index(['The Dark Knight', 'Schindler's List', 'Forrest Gump', 'Inception'], dtype='object')
[9.  8.9 8.8 8.7]
The Dark Knight     9.0
Schindler's List    8.9
Forrest Gump        8.8
Inception           8.7
dtype: float64


In [79]:
movie_dict = {
    "The Dark Knight": 9.0,
    "Schindler's List": 8.9,
    "Forrest Gump": 8.8,
    "Inception": 8.7
}
ser = pd.Series(movie_dict)
print(movie_dict.keys())
print(movie_dict.values())
print("\n")
print(ser.index)
print(ser.values)
print(ser)

dict_keys(['The Dark Knight', "Schindler's List", 'Forrest Gump', 'Inception'])
dict_values([9.0, 8.9, 8.8, 8.7])


Index(['The Dark Knight', 'Schindler's List', 'Forrest Gump', 'Inception'], dtype='object')
[9.  8.9 8.8 8.7]
The Dark Knight     9.0
Schindler's List    8.9
Forrest Gump        8.8
Inception           8.7
dtype: float64


In [ ]:
# Read csv document

In [82]:
df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/archived_data/archived_daily_case_updates/02-14-2020_1123.csv")
df


Province/State  Country/Region          Last Update  Confirmed  Deaths  \
0             Hubei  Mainland China  2020-02-14 10:03:03      51986    1318   
1         Guangdong  Mainland China  2020-02-14 12:53:02       1261       2   
2             Henan  Mainland China  2020-02-14 12:53:02       1184      11   
3          Zhejiang  Mainland China  2020-02-14 14:13:15       1155       0   
4             Hunan  Mainland China  2020-02-14 09:23:04        988       2   
..              ...             ...                  ...        ...     ...   
69      Madison, WI              US  2020-02-05 21:53:02          1       0   
70       Orange, CA              US  2020-02-01 19:53:03          1       0   
71  San Antonio, TX              US  2020-02-13 18:53:02          1       0   
72      Seattle, WA              US  2020-02-09 07:03:04          1       0   
73        Tempe, AZ              US  2020-02-01 19:43:03          1       0   

    Recovered  
0        3900  
1         362  
2         357  
3         403  
4         364  
..        ...  
69          0  
70          0  
71          0  
72          1  
73          0  

[74 rows x 6 columns]

In [84]:
# Read JSON file

In [85]:
df = pd.read_json("https://python4ds.s3-ap-northeast-1.amazonaws.com/movies.json")
df

title  rating
0   The Dark Knight     9.0
1  Schindler's List     8.9
2      Forrest Gump     8.8
3         Inception     8.7

In [ ]:
# Read data from database
# With SQL command

In [83]:
import sqlite3

# Creating a demo.db database in working directory
conn = sqlite3.connect('demo.db')
# Importing a table
movie_ratings = [9.0, 8.9, 8.8, 8.7]
movie_titles = ["The Dark Knight", "Schindler's List", "Forrest Gump", "Inception"]
df = pd.DataFrame()
df["title"] = movie_titles
df["rating"] = movie_ratings
df.to_sql("movies", index=False, con=conn, if_exists='replace')
# Importing data from demo.movies
query_str = """
SELECT *
    FROM movies
    WHERE rating < 9.0;
"""
pd.read_sql(query_str, con=conn)

title  rating
0  Schindler's List     8.9
1      Forrest Gump     8.8
2         Inception     8.7