In [1]:
import requests
from bs4 import BeautifulSoup

In [3]:
def get_price_rank():
    query_str_parameters = {
        't': 'pri',
        'e': 'tse',
        'n': '100'
    }
    request_url = "https://tw.stock.yahoo.com/d/i/rank.php"
    response = requests.get(request_url, params=query_str_parameters)
    soup = BeautifulSoup(response.text)
    stock_tickers = []
    stock_names = []
    for e in soup.select(".name a"):
        stock_ticker = e.text.split()[0]
        stock_name = e.text.split()[1]
        stock_tickers.append(stock_ticker)
        stock_names.append(stock_name)
    prices = [float(e.text) for e in soup.select('.name+ td')]
    return stock_tickers, stock_names, prices

In [4]:
stock_tickers, stock_names, prices = get_price_rank()

In [5]:
print(stock_tickers)
print(stock_names)
print(prices)

['3008', '6415', '5269', '6409', '6669', '2454', '1590', '3406', '2207', '3661', '8454', '2330', '3533', '1476', '2379', '6531', '2327', '8464', '2059', '2049', '3653', '2395', '3563', '9921', '3443', '6504', '3034', '6414', '2912', '4968', '8341', '2227', '9914', '6230', '2357', '2474', '2345', '2404', '3665', '1256', '4137', '3413', '2308', '9910', '8070', '4551', '1477', '2492', '1707', '8462', '3023', '2383', '6491', '3515', '8081', '6670', '1325', '2439', '6582', '5215', '8422', '2360', '4536', '3130', '3376', '6416', '6533', '6706', '8016', '1537', '6271', '6269', '2458', '4439', '4958', '2377', '6715', '4766', '1558', '6456', '2707', '8499', '6278', '4438', '8046', '4912', '4763', '4119', '4943', '4977', '3532', '6213', '5871', '2231', '8480', '3044', '1232', '5434', '6464', '1760']
['大立光', '矽力-KY', '祥碩', '旭隼', '緯穎', '聯發科', '亞德客-KY', '玉晶光', '和泰車', '世芯-KY', '富邦媒', '台積電', '嘉澤', '儒鴻', '瑞昱', '愛普', '國巨', '億豐', '川湖', '上銀', '健策', '研華', '牧德', '巨大', '創意', '南六', '聯詠', '樺漢', '統一超', '立積', '

In [8]:
from statistics import median

ky_prices = [price for stock_name, price in zip(stock_names, prices) if "KY" in stock_name]
median(ky_prices)

137.0

In [11]:
# 17 of 100 companies are high prices stock with "KY" sign.
ky_prices = list()
for n, p in zip(stock_names, prices):
    if 'KY' in n:
        ky_prices.append(p)
print(len(ky_prices))


17


In [12]:
ky_prices

[1755.0,
 673.0,
 610.0,
 209.0,
 204.5,
 203.5,
 161.0,
 137.0,
 137.0,
 132.5,
 132.0,
 128.5,
 127.5,
 125.5,
 125.5,
 124.0,
 121.0]

In [13]:
## Python 一直以來都非常適合資料處理，但她的分析能力很薄弱，`pandas` 的開發有助於補足 Python 資料分析的需求，讓使用者能夠在 Python 中執行完整的資料分析流程，而無需切換到 data-centric 的特定語言，如 R。

In [17]:
import pandas as pd

df = pd.DataFrame()
df["ticker"] = stock_tickers
df["name"] = stock_names
df["price"] = prices
df.head()

ticker   name   price
0   3008    大立光  3900.0
1   6415  矽力-KY  1755.0
2   5269     祥碩  1705.0
3   6409     旭隼   970.0
4   6669     緯穎   786.0

In [18]:
df.tail()

ticker  name  price
95   3044    健鼎  120.5
96   1232   大統益  120.0
97   5434    崇越  120.0
98   6464   台數科  120.0
99   1760  寶齡富錦  118.5

In [19]:
df['price']

0     3900.0
1     1755.0
2     1705.0
3      970.0
4      786.0
       ...  
95     120.5
96     120.0
97     120.0
98     120.0
99     118.5
Name: price, Length: 100, dtype: float64

In [20]:
df['name']

0       大立光
1     矽力-KY
2        祥碩
3        旭隼
4        緯穎
      ...  
95       健鼎
96      大統益
97       崇越
98      台數科
99     寶齡富錦
Name: name, Length: 100, dtype: object

In [21]:
# Get data of a single company.
df.dtypes

ticker     object
name       object
price     float64
dtype: object

In [22]:
df.loc[0, :]

ticker    3008
name       大立光
price     3900
Name: 0, dtype: object

In [23]:
df.loc[0, ]

ticker    3008
name       大立光
price     3900
Name: 0, dtype: object

In [24]:
# Get data of companies with "KY" sign.
df[df["name"].str.contains('KY')]

ticker     name   price
1    6415    矽力-KY  1755.0
6    1590   亞德客-KY   673.0
9    3661    世芯-KY   610.0
38   3665    貿聯-KY   209.0
39   1256  鮮活果汁-KY   204.5
40   4137    麗豐-KY   203.5
59   5215    科嘉-KY   161.0
73   4439    冠星-KY   137.0
74   4958    臻鼎-KY   137.0
79   6456   GIS-KY   132.5
81   8499    鼎炫-KY   132.0
85   4912  聯德控股-KY   128.5
86   4763    材料-KY   127.5
88   4943    康控-KY   125.5
89   4977    眾達-KY   125.5
92   5871    中租-KY   124.0
94   8480    泰昇-KY   121.0

In [26]:
df[df["name"].str.contains('KY')]['price']

1     1755.0
6      673.0
9      610.0
38     209.0
39     204.5
40     203.5
59     161.0
73     137.0
74     137.0
79     132.5
81     132.0
85     128.5
86     127.5
88     125.5
89     125.5
92     124.0
94     121.0
Name: price, dtype: float64

In [28]:
df[df["name"].str.contains("KY")]["price"].median()

137.0

In [35]:
## pandas 提供了新的資料結構

In [36]:
# run in bash shell
!pip install pandas

You should consider upgrading via the 'c:\users\paul\anaconda3\python.exe -m pip install --upgrade pip' command.


In [37]:
# run in python console
import pandas as pd

In [39]:
movie_ratings = [8.0, 7.3, 8.5, 8.6]
ser = pd.Series(movie_ratings)

<class 'pandas.core.series.Series'>
0    8.0
1    7.3
2    8.5
3    8.6
dtype: float64
8.6


In [40]:
# Pandas add index key.
print(type(ser))
print(ser)
print(ser[3])

<class 'pandas.core.series.Series'>
0    8.0
1    7.3
2    8.5
3    8.6
dtype: float64
8.6


In [42]:
movie_titles = ['The Avengers', 'Avengers: Age of Ultron', 'Avengers: Infinite War', 'Avengers: Endgame']
ser = pd.Series(movie_ratings, index = movie_titles)
ser

The Avengers               8.0
Avengers: Age of Ultron    7.3
Avengers: Infinite War     8.5
Avengers: Endgame          8.6
dtype: float64

In [43]:
type(ser.values)

numpy.ndarray

In [46]:
print(ser.values)
print(ser.index)

[8.  7.3 8.5 8.6]
Index(['The Avengers', 'Avengers: Age of Ultron', 'Avengers: Infinite War',
       'Avengers: Endgame'],
      dtype='object')


In [47]:
# Vectorization.
ser*10

The Avengers               80.0
Avengers: Age of Ultron    73.0
Avengers: Infinite War     85.0
Avengers: Endgame          86.0
dtype: float64

In [48]:
# Boolean type is applicable.
ser[ser >= 8]

The Avengers              8.0
Avengers: Infinite War    8.5
Avengers: Endgame         8.6
dtype: float64

In [50]:
ser['Avengers: Infinite War']

8.5

In [52]:
ser[2]

8.5

In [57]:
avengers = pd.DataFrame()
avengers['movie'] = movie_titles
avengers['rating'] = movie_ratings
avengers

movie  rating
0             The Avengers     8.0
1  Avengers: Age of Ultron     7.3
2   Avengers: Infinite War     8.5
3        Avengers: Endgame     8.6

In [58]:
type(avengers)

pandas.core.frame.DataFrame

In [59]:
avengers.index

RangeIndex(start=0, stop=4, step=1)

In [60]:
avengers.columns

Index(['movie', 'rating'], dtype='object')

In [65]:
avengers['movie'].values

array(['The Avengers', 'Avengers: Age of Ultron',
       'Avengers: Infinite War', 'Avengers: Endgame'], dtype=object)

In [68]:
avengers['movie'].values

array(['The Avengers', 'Avengers: Age of Ultron',
       'Avengers: Infinite War', 'Avengers: Endgame'], dtype=object)

In [69]:
# Set is useful for joint, union and independent...
odds_index = pd.Index([1, 3, 5, 7, 9])
primes_index = pd.Index([2, 3, 5, 7])
print(odds_index & primes_index) # and
print(odds_index | primes_index) # or
print(odds_index ^ primes_index) # exclusive or

Int64Index([3, 5, 7], dtype='int64')
Int64Index([1, 2, 3, 5, 7, 9], dtype='int64')
Int64Index([1, 2, 9], dtype='int64')


In [70]:
# Joint
odds_index & primes_index

Int64Index([3, 5, 7], dtype='int64')

In [71]:
odds_index | primes_index

Int64Index([1, 2, 3, 5, 7, 9], dtype='int64')

In [72]:
# XOR（Exclusive OR）
odds_index ^ primes_index

Int64Index([1, 2, 9], dtype='int64')

In [ ]:
odds_index ^ primes_index

In [73]:
odds_index.difference(primes_index)

Int64Index([1, 9], dtype='int64')

In [75]:
primes_index.difference(odds_index)

Int64Index([2], dtype='int64')

In [ ]:
...

In [76]:
movie_ratings = [9.0, 8.9, 8.8, 8.7]
ser = pd.Series(movie_ratings)
print(ser)

0    9.0
1    8.9
2    8.8
3    8.7
dtype: float64


In [77]:
movie_ratings = [9.0, 8.9, 8.8, 8.7]
movie_titles = ["The Dark Knight", "Schindler's List", "Forrest Gump", "Inception"]
ser = pd.Series(movie_ratings, index=movie_titles)
print(ser.index)
print(ser.values)
print(ser)

Index(['The Dark Knight', 'Schindler's List', 'Forrest Gump', 'Inception'], dtype='object')
[9.  8.9 8.8 8.7]
The Dark Knight     9.0
Schindler's List    8.9
Forrest Gump        8.8
Inception           8.7
dtype: float64


In [79]:
movie_dict = {
    "The Dark Knight": 9.0,
    "Schindler's List": 8.9,
    "Forrest Gump": 8.8,
    "Inception": 8.7
}
ser = pd.Series(movie_dict)
print(movie_dict.keys())
print(movie_dict.values())
print("\n")
print(ser.index)
print(ser.values)
print(ser)

dict_keys(['The Dark Knight', "Schindler's List", 'Forrest Gump', 'Inception'])
dict_values([9.0, 8.9, 8.8, 8.7])


Index(['The Dark Knight', 'Schindler's List', 'Forrest Gump', 'Inception'], dtype='object')
[9.  8.9 8.8 8.7]
The Dark Knight     9.0
Schindler's List    8.9
Forrest Gump        8.8
Inception           8.7
dtype: float64


In [ ]:
# Read csv document

In [82]:
df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/archived_data/archived_daily_case_updates/02-14-2020_1123.csv")
df


Province/State  Country/Region          Last Update  Confirmed  Deaths  \
0             Hubei  Mainland China  2020-02-14 10:03:03      51986    1318   
1         Guangdong  Mainland China  2020-02-14 12:53:02       1261       2   
2             Henan  Mainland China  2020-02-14 12:53:02       1184      11   
3          Zhejiang  Mainland China  2020-02-14 14:13:15       1155       0   
4             Hunan  Mainland China  2020-02-14 09:23:04        988       2   
..              ...             ...                  ...        ...     ...   
69      Madison, WI              US  2020-02-05 21:53:02          1       0   
70       Orange, CA              US  2020-02-01 19:53:03          1       0   
71  San Antonio, TX              US  2020-02-13 18:53:02          1       0   
72      Seattle, WA              US  2020-02-09 07:03:04          1       0   
73        Tempe, AZ              US  2020-02-01 19:43:03          1       0   

    Recovered  
0        3900  
1         362  
2         357  
3         403  
4         364  
..        ...  
69          0  
70          0  
71          0  
72          1  
73          0  

[74 rows x 6 columns]

In [84]:
# Read JSON file

In [85]:
df = pd.read_json("https://python4ds.s3-ap-northeast-1.amazonaws.com/movies.json")
df

title  rating
0   The Dark Knight     9.0
1  Schindler's List     8.9
2      Forrest Gump     8.8
3         Inception     8.7

In [ ]:
# Read data from database
# With SQL command

In [83]:
import sqlite3

# Creating a demo.db database in working directory
conn = sqlite3.connect('demo.db')
# Importing a table
movie_ratings = [9.0, 8.9, 8.8, 8.7]
movie_titles = ["The Dark Knight", "Schindler's List", "Forrest Gump", "Inception"]
df = pd.DataFrame()
df["title"] = movie_titles
df["rating"] = movie_ratings
df.to_sql("movies", index=False, con=conn, if_exists='replace')
# Importing data from demo.movies
query_str = """
SELECT *
    FROM movies
    WHERE rating < 9.0;
"""
pd.read_sql(query_str, con=conn)

title  rating
0  Schindler's List     8.9
1      Forrest Gump     8.8
2         Inception     8.7